"use client";
import {useEffect,useRef,useState} from 'react';
import {LoaderCircle} from 'lucide-react';
export default function LiveMap({live,demo}:{live:any;demo:boolean}){
 const el=useRef<HTMLDivElement>(null),map=useRef<any>(null),marker=useRef<any>(null),leaflet=useRef<any>(null);const[ready,setReady]=useState(false),[failed,setFailed]=useState(false);
 useEffect(()=>{let cancel=false;import('leaflet').then(L=>{if(cancel||!el.current)return;leaflet.current=L;const m=L.map(el.current,{scrollWheelZoom:false,zoomControl:true}).setView([27.89,-82.55],10);map.current=m;const tiles=L.tileLayer('https://{s}.basemaps.cartocdn.com/dark_all/{z}/{x}/{y}{r}.png',{attribution:'&copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> &copy; <a href="https://carto.com/attributions">CARTO</a>',maxZoom:19}).addTo(m);tiles.on('tileerror',()=>setFailed(true));tiles.on('load',()=>setReady(true));setReady(true)}).catch(()=>setFailed(true));return()=>{cancel=true;map.current?.remove();map.current=null}},[]);
 useEffect(()=>{if(!ready||!map.current)return;marker.current?.remove();const point=live|| (demo?{lat:27.9506,lng:-82.4572,venue:'Live venue preview'}:null);if(point){const L=leaflet.current;const icon=L.divIcon({className:'dj-map-icon',html:'<div class="dj-pin"><svg width="28" height="28" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M3 14v-3a9 9 0 0 1 18 0v3M3 13h4v8H3zM17 13h4v8h-4z"/></svg></div>',iconSize:[54,54],iconAnchor:[27,27]});const popup=document.createElement('div');popup.textContent=demo&&!live?'Preview only — not a live check-in':point.venue;marker.current=L.marker([point.lat,point.lng],{icon}).addTo(map.current).bindPopup(popup).openPopup();map.current.flyTo([point.lat,point.lng],14,{duration:1.2})}else map.current.setView([27.89,-82.55],10)},[live?.id,live?.lat,live?.lng,live?.venue,demo,ready]);
 return <><div ref={el} className="live-map" aria-label="Interactive map of Tampa Bay showing Dreezz’s published live venue"/>{!ready&&!failed&&<div className="map-loading"><LoaderCircle className="spin"/> Finding the frequency…</div>}{failed&&<div className="map-error">Map tiles couldn’t load. Live venue details are shown alongside the map.</div>}</>
}
