"use client";

export default function FanBackstage({data,busy,save}:{data:any;busy:boolean;save:(payload:any)=>Promise<boolean>}){
 const actions=(data.fanActions||[]).filter((action:any)=>action.type!=='vote');
 return <div className="admin-grid">
  <div><h2>Fan Lab controls</h2><p>Keep this simple: one current poll, one live-room source and one official custom-blend checkout link.</p><form className="admin-form" onSubmit={e=>{e.preventDefault();void save({...Object.fromEntries(new FormData(e.currentTarget)),action:'settings'})}}><label>Poll question<input name="pollQuestion" defaultValue={data.settings.pollQuestion||'What should Dreezz make next?'} maxLength={180}/></label><label>Poll options — one per line<textarea name="pollOptions" defaultValue={data.settings.pollOptions||'Rooftop sunset set\nDeep after-hours set\nR&B × house blend\nFan-voted mix'} rows={6}/></label><label>Live Room embed URL<input type="url" name="liveStreamUrl" defaultValue={data.settings.liveStreamUrl||''} placeholder="https://...embed..."/></label><small>Use an embeddable player URL from YouTube, Twitch or the chosen streaming provider.</small><label>Custom blend checkout / product URL<input type="url" name="blendUrl" defaultValue={data.settings.blendUrl||''} placeholder="https://"/></label><small>Leave blank and fans can still submit a custom-blend inquiry. Add a checkout URL when Dreezz is ready to sell it directly.</small><button disabled={busy} className="button lime">Save Fan Lab</button></form></div>
  <div><h2>Requests & blend leads</h2>{!actions.length&&<p className="admin-notice">Nothing here yet. Song requests and custom blend inquiries will land here.</p>}{actions.map((action:any)=>{let payload:any={};try{payload=JSON.parse(action.payload||'{}')}catch{}return <article key={action.id}><span className="status">{action.type==='blend'?'CUSTOM BLEND':'MUSIC REQUEST'}</span><h3>{action.type==='blend'?(payload.occasion||'Custom blend'):(payload.track||'Track request')}</h3>{action.type==='song'&&<><p>{payload.artist||'Artist not specified'}</p><p>{payload.note||'No note added.'}</p></>}{action.type==='blend'&&<><p>{payload.vibe}</p><small>References: {payload.references||'None'} · Length: {payload.length||'Open'} · Budget: {payload.budget||'Open'} · Due: {payload.due||'Flexible'}</small></>}<p>{action.name||'Fan'}{action.email?' · '+action.email:''}</p>{action.email&&<a className="button mt-3" href={'mailto:'+encodeURIComponent(action.email)+'?subject='+encodeURIComponent(action.type==='blend'?'Your Dreezz custom blend':'Your Dreezz music request')}>Reply by email ↗</a>}</article>})}</div>
 </div>
}
